config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',     to: 'users#new'
  match '/signin',     to: 'sessions#new'
  match '/signout',    to: 'sessions#destroy', via: :delete

  match '/help',       to: 'static_pages#help'
  match '/about',      to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/lilly',      to: 'static_pages#lilly'
  match '/careerfair', to: 'static_pages#careerfair'
  match '/ncaa',       to: 'static_pages#ncaa'
  match '/simon',      to: 'static_pages#simon'
  match '/oneamerica', to: 'static_pages#oneamerica'
  match '/quicken',    to: 'static_pages#quicken'
  match '/blackbaud',  to: 'static_pages#blackbaud'
  match '/docz',       to: 'static_pages#docz'
  match '/wellpoint',  to: 'static_pages#wellpoint'
  match '/pacers',     to: 'static_pages#pacers'
  match '/cavaliers',   to: 'static_pages#cavaliers'
  match '/rci',         to: 'static_pages#rci'
  match '/minnesota',   to: 'static_pages#minnesota'
  match '/bigten',      to: 'static_pages#bigten'
  match '/exacttarget', to: 'static_pages#exacttarget'
  match '/bkd',         to: 'static_pages#bkd'
  match '/isc',         to: 'static_pages#isc' 
  match '/herffjones',  to: 'static_pages#herffjones'      

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_filter :signed_in_user

  def home
  	if signed_in?
  	@micropost = current_user.microposts.build
  	@feed_items = current_user.feed.paginate(page: params[:page])
  	@micropost_items = Micropost.all
    end  
  end

  def help
  end

  def about
  end

  def contact
  end

  def lilly
    render :layout => false
  end

  def careerfair
  end

  def cavaliers
    render :layout => false
  end

  def pacers
    render :layout => false
  end

  def wellpoint
    render :layout => false
  end

  def docz
    render :layout => false
  end

  def blackbaud
    render :layout => false
  end

  def quicken
    render :layout => false
  end

  def oneamerica
    render :layout => false
  end

  def simon
    render :layout => false
  end

  def ncaa
    render :layout => false
  end

  def minnesota
    render :layout => false
  end

  def bigten
    render :layout => false
  end

  def bkd
    render :layout => false
  end

  def exacttarget
    render :layout => false
  end

  def isc
    render :layout => false
  end

  def herffjones
    render :layout => false
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/bigten.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?o9KLiUnPFHDLfkiUzwXgbbupIQ5ykst4';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<div class="pull-left boothlogo"><%= image_tag("big_tenLogo.png") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 10:00am-11:00am. Nov.30, 10:00am-11:00am.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for multiple disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern, entry and experienced level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Big Ten Conference Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/careerfair.html.erb
<div class="center hero-unit">
	<h1>Virtual Booth Page</h1>
	<br />
	<p>
		Visit the employer booths by clicking the corresponding buttons below.
	</p>
</div>
<span class="logobutton">
<%= link_to image_tag("Blackbaud_Logo.jpg", alt: "Blackbaud's Virtual Booth"), blackbaud_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("NCAA_enchanced_logo_to_fit_badge.jpg", alt: "NCAA's Virtual Booth"), ncaa_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("OA_red_blue.jpg", alt: "One America's Virtual Booth"), oneamerica_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("pacers_sports_entertainment.jpg", alt: "Pacers' Virtual Booth" ), pacers_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("RCI_Logo.jpg", alt: "RCI's Virtual Booth"), rci_path %> 
</span>
<br />
<br />
<span class="logobutton">
<%= link_to image_tag("SimonPropInc2768.jpg", alt: "Simon Property Group's Virtual Booth"), simon_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("minnesota.jpg", alt: "University of Minnesota's Virtual Booth"), minnesota_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("new-cavaliers-primary-logo.jpg", alt: "Cavaliers' Virtual Booth"), cavaliers_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("WellPoint_PMS_blue_red_horz_04_09.jpg", alt: "Wellpoint's Virtual Booth"), wellpoint_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("lilly_logo.png", alt: "Eli Lilly & Companies' Virtual Booth"), lilly_path %> 
</span>
<br />
<br />
<span class="logobutton">
<%= link_to image_tag("small_doz.png", alt: "Dauby O'Connor & Zaleski's Virtual Booth"), docz_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("small_bigten.png", alt: "Big Ten Conference Virtual Booth"), bigten_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("small_bkd.jpg", alt: "BKD Conference Virtual Booth"), bkd_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("small_exacttarget.png", alt: "ExactTarget Conference Virtual Booth"), exacttarget_path %> 
</span>
<br />
<br />
<span class="logobutton">
<%= link_to image_tag("small_isc.jpg", alt: "Indiana Sports Corp Conference Virtual Booth"), isc_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("small_herff.png", alt: "Herff Jones Conference Virtual Booth"), herffjones_path %> 
</span>
<span class="logobutton">
<%= link_to image_tag("big_quicken.png", alt: "Quicken Conference Virtual Booth"), quicken_path %> 
</span>
<%#= link_to image_tag("virtualCareerFairLogo.png", alt: "Big Ten Virtual Career Fair"), 'http://bigtenvirtualcareerfair.com' %>

app/views/static_pages/cavaliers.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?o9LOkxRprtNJNt0Ej25LNfzEpNF6hlyI';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<div class="pull-left boothlogo"><%= image_tag("big_cavaliers.gif") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 10:00am-11:00am. Nov.30, 2:00pm-3:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for accounting, communications, information technology, journalism, marketing, non-profit, public relations and sales disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern and entry level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Cavaliers Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/docz.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?o9LqNLaXcReWzZhgleKTvrBIlou3GqNF';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
<div class="pull-left"><%= image_tag("big_doz.tiff") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.30, 2:00 - 3:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for the accounting discipline.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern, entry and experienced level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Dauby O'Connor Zaleski Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/herffjones.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?oUjB0l0RxL8wm7GByHvyRNYGorQ0NC3k';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<div class="pull-left"><%= image_tag("big_herff.png") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 2:00pm-4:00pm. Nov.30, 2:00pm-4:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for sales disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an internship and experienced level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Herff Jones Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
	<% if current_user.admin? %>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="span8">
		<h3>Jobs Listing</h3>
		<%= render 'shared/feed' %>
	</div>
	<% else %>
	<div class="span8">
		<%= render 'shared/micropost' %>
	</div>
	<% end %>
</div>

<% else %>
	<div class="center hero-unit">
		<h1>Welcome to the Virtual Career Fair</h1>
		<p>
			This is the home page for the <a href="http://bigtenvirtualcareerfair.com">Big Ten Virtual Career Fair</a>
		</p>
		<br />
			<%= link_to "Sign up now!", signup_path, class: "btn-large btn-primary" %>
	</div>
	<div class="logo">
	<%#= link_to image_tag("virtualCareerFairLogo.png", alt: "Big Ten Virtual Career Fair"), 'http://bigtenvirtualcareerfair.com' %>
	<%#= link_to image_tag("eli_lilly.png", alt: "Lilly"), 'http://lilly.com' %>
	</div>
<% end %>

app/views/static_pages/isc.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?oL4huO32RupLkVwaTqKlJdapn4MRqfOB';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<div class="pull-left boothlogo"><%= image_tag("big_isc.jpg") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 10:00am-12:00pm. Nov.30, 10:00am-12:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for accounting, communications, fundraising, hospitality, journalism, marketing, public relations and sales disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Indiana Sports Corp Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/lilly.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?o9Z1ondm4H3kBBx3TIY2hUwacGXvw7Av';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
<div class="pull-left"><%= image_tag("big_lilly_logo.png") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 11:00am-2:00pm. Nov.30, 11:00am-2:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for accounting, agriculture, chemistry, communications, engineering, human resources, information technology, marketing, pharmaceuticals, and sales disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern, entry and experienced level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the Eli Lilly & Company Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>

<div class="span16 alert alert-warning block-message"><p><h1>To look at Eli Lilly & Company jobs please go to http://www.lilly.com/careers/Pages/default.aspx</h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<!--<div class="pull-left span5 alert alert-info block-message"><p><h3>IT ANALYST</h3></p><p>Manufacturing IT supports operational excellence and productivity efforts through utilization of information and technology. This includes maximizing and exploiting existing systems at all levels, benchmarking and replicating as much as possible and using data to drive process improvements and productivity. This Manufacturing IT position, hosted at US Distribution – Plainfield, IN Distribution Center, partners with business operations and other functional areas (outside of US Distribution) to identify opportunities and lead activities that directly supports US Distribution’s key objectives. The position requires a variety of skill sets including business analysis (60%) and technical expertise (40%). This position is an integral part of the local IT team supporting the logistics business and warehouse operations, utilizing local applications as well as SAP-WM/IM/O2C. In addition, this position will have responsibility for understanding, implementation and support of the US Distribution Business Intelligence Strategy and reporting needs.</p><br />
<p>Project Delivery – lead the delivery of software/system solutions.</p>
<p>Be an expert and resource in the business use of certain IT applications, ensure the systems remain in a validated state, and are appropriately managed throughout their lifecycle.</p>
<p>Stay current with regulatory, legal, or quality requirements which impact our business areas, and ensure solution requirements comply.</p>
<p>Ensure that incident, problem, configuration, and change release management are all performed in alignment and compliance with business and quality needs.</p>
<p>Partner with IT peers across manufacturing and solution services to identify solutions to meet business partner needs.</p>
<p>Research and evaluatealternative technical solutions and develop business cases to support the business
Resolve challenging issues via break-fix testing, trouble tickets and/or change request.</p>
<p>Produce and maintain project and/or validation documentation, often in conjunction with a Validation or documentation specialist.</p>
<p>Influence the business to drive value and implement the appropriate technical solutions.</p>
<p>Accurately translate business processes, which may span multiple areas, into technical terms and vice versa</p>
<p>Find innovative ways to use existing and new IT-enabled solution to drive business value</p></div>

<div class="pull-right span5 alert alert-info block-message"><p><h3>RESEARCH SCIENTIST</h3></p><p>	
· Using appropriate biophysical tools and techniques to characterize the physiochemical properties of in-process materials, drug substance and drug product.
<br /><br />
· All aspects of laboratory operations including sample receipt, data generation, verification and interpretation, aberrant data investigations, instrument qualification, operation and trouble-shooting, and all supporting documentation for such activities, including appropriate use of LIMS and other informatics interfaces within the laboratory.
<br /><br />
· Participating as biophysical lead in and / or lead cross-functional teams, and effectively collaborate with other groups in Bioprocess and Bioproduct Development, Discovery, MS&T and Manufacturing, as well as contract research and other external organizations.
<br /><br />
· Authorship / review of technical reports and regulatory documents.
<br /><br />
· Identification and implementation of new technologies / capabilities.
<br /><br />
· Staying informed on relevant regulatory initiatives/ requirements
<br /><br />
· Coaching, training, and administration of performance management to personnel (primarily, but not limited to, direct reports)
<br /><br />
· Leading / supporting implementation of organizational strategic initiatives in support of the Lilly pipeline
<br /><br />
· Ensuring work is aligned with all relevant Development Quality, regulatory and HSE requirements.
<br /><br />
Basic Qualifications:
<br /><br />
Ph.D. in Biochemistry / Biophysics / Biophysical Chemistry, Chemical / Biochemical Engineering, or related field.<br /><br />
Thorough understanding of structure / conformation / function and relevant physical / chemical degradation pathways of proteins and other biomolecules.<br /><br />
Comprehensive knowledge of and experience with multiple experimental biophysical techniques used to assess higher order structure of proteins and other biomolecules.<br /><br />
Additional Skills/Preferences<br /><br />
Up to 2 years experience in pharmaceutical or biotech industry in utilizing biophysical techniques to characterize biomolecules<br /><br />
Experience with computational tools and techniques and the development of mathematical models to describe experimental data<br /><br />
Experience supervising direct reports<br /><br />
Demonstrated technical and scientific leadership skills<br /><br />
Proven ability to adapt and learn quickly<br /><br />
Demonstrated ability to work productively in both an interdisciplinary team environment and work  independently from the bench (design experiments, generate data and interpret results)<br /><br />
Effective oral and written communication skills<br /><br />
Demonstrated self-management, task planning and organizing skills; as well as problem solving and decision making skills</p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/minnesota.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
		  <!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?o9ZFkQVOuzRQqUkHqjRPzJXAgQDdkgED';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
<div class="pull-left boothlogo"><%= image_tag("big_minnesota.jpg") %></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hours Available: Nov.29, 2:00pm-3:00pm. Nov.30, 2:00pm-3:00pm.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Positions and internships available for administrative support, communications, customer service, fundraising, graphic design, journalism, management, marketing, public relations and sales disciplines.</h4></div>
<div class="pull-right span6 alert alert-info block-message"><h4>Hiring on an intern level.</h4></div>
<div class="span16 alert alert-success block-message"><p><h1>Welcome to the University of Minnesota Virtual Booth! Please introduce and tell us about yourself in the chat box, once it pops up, and our representatives will be speaking with you shortly.</h1></p></div>
<div class="span16 alert alert-success block-message"><p><h1>To learn more about our internships go <a href="http://vid.us/7twky" target="_blank">here!</a></h1></p></div>
<!--<div class="span16 alert alert-warning block-message"><p><h1>While you are waiting please feel free to look at the jobs listed below.</h1></p></div>-->
<%= render 'layouts/footer' %>
		</div>
	</body>
</html>