config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup',     to: 'users#new'
  match '/signin',     to: 'sessions#new'
  match '/signout',    to: 'sessions#destroy', via: :delete

  match '/help',       to: 'static_pages#help'
  match '/about',      to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/lilly',      to: 'static_pages#lilly'
  match '/careerfair', to: 'static_pages#careerfair'
  match '/ncaa',       to: 'static_pages#ncaa'
  match '/simon',      to: 'static_pages#simon'
  match '/oneamerica', to: 'static_pages#oneamerica'
  match '/quicken',    to: 'static_pages#quicken'
  match '/blackbaud',  to: 'static_pages#blackbaud'
  match '/docz',       to: 'static_pages#docz'
  match '/wellpoint',  to: 'static_pages#wellpoint'
  match '/pacers',     to: 'static_pages#pacers'
  match '/cavaliers',   to: 'static_pages#cavaliers'
  match '/rci',         to: 'static_pages#rci'
  match '/minnesota',   to: 'static_pages#minnesota'
  match '/bigten',      to: 'static_pages#bigten'
  match '/exacttarget', to: 'static_pages#exacttarget'
  match '/bkd',         to: 'static_pages#bkd'
  match '/isc',         to: 'static_pages#isc' 
  match '/herffjones',  to: 'static_pages#herffjones'      

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to image_tag("lilly_small.png", alt: "Lilly"), 'http://lilly.com' %>
		<%= link_to image_tag("simon.png", alt: "Simon"), 'http://simon.com' %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<!--<li><a href="http://news.railstutorial.org/">News</a></li>-->
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
		<%= link_to "virtual career fair", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",           root_path	        %></li>
					<li><%= link_to "Help",           help_path	        %></li>
					
					
						<% if signed_in? %>
						<li><%= link_to "Career Fair",    careerfair_path	%></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", user_path(current_user) %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<% if current_user.admin? %>
									<li><%= link_to "Resumes", users_path %></li>
								<% else %>
								<% end %>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>	
						</li>
						<% else %>
							<li><%= link_to "Sign in", signin_path	%></li>
						<% end %>
						
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title><%= full_title(yield(:title)) %></title>
		  <%= stylesheet_link_tag    "application", media: "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
		  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>